// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.EFCore.Data;

#nullable disable

namespace WebAPI.EFCore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230213130337_SeedingData")]
    partial class SeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.EFCore.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryOrder = 3,
                            CreatedDate = new DateTime(2023, 2, 13, 18, 3, 37, 681, DateTimeKind.Local).AddTicks(8879),
                            Name = "HTC"
                        },
                        new
                        {
                            Id = 2,
                            CategoryOrder = 4,
                            CreatedDate = new DateTime(2023, 2, 13, 18, 3, 37, 681, DateTimeKind.Local).AddTicks(8894),
                            Name = "LG"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
